version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - cluster.initial_master_nodes=elasticsearch
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - node.master=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPT=-Xms1g -Xmx1g"
    expose:
      - 9200
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.5.0
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

networks:
  back_net:
  front_net:
